In [68]:
import numpy as np
import pandas as pd

b_data = pd.read_excel("data/basic_data.xlsx")
a_data = pd.read_excel("data/advanced_data.xlsx")
# Rename the merge columsn
b_data.rename(columns={"Season Start":"year", "Player Name":"player"}, inplace=True)
data = b_data.merge(a_data, on=["year", "player"])
data = data[data.year >= 2000]
salary_caps = pd.read_csv("data/salary_cap.csv", header=None).iloc[:, :2]
salary_caps.rename(columns={0:"year", 1:"salary_cap"}, inplace=True)
salary_caps["year"] = salary_caps["year"].apply(lambda val: int(str(val)[:4]))
salary_caps["salary_cap"] = salary_caps["salary_cap"].apply(lambda val: 
                                                            float(val.replace("$", "").replace(",","")))
data = data.merge(salary_caps, on=["year"])
data.rename(columns={"Player Salary in $":"salary"}, inplace=True)
# Modify the target variable to make it a percentage
target = "salary"
data = data[pd.isna(data[target])==False]
data[target] = data.apply(lambda val: val[target]/val["salary_cap"], axis=1)

In [69]:
# Save the data as a pickle
data.to_pickle("data/main.df")

In [67]:
data

,#,year,player,Player Salary in $,Pos,Age,Tm,G,GS,MP,...,adjusted_worp,estimated_position,bbref_pos,age_on_feb_1,yrs_experience,height,weight,rounded_position,rounded_age,salary_cap
0,14648.0,2000.0,A.C. Green,0.063380,PF,36.0,LAL,82.0,82.0,1929.0,...,2.5,3.7,4.0,36.33,14.0,81.0,220.0,4.0,36.0,35500000.0
3,14946.0,2000.0,Aaron Williams,0.063380,PF,28.0,WAS,81.0,0.0,1545.0,...,4.4,4.0,4.0,28.33,5.0,81.0,220.0,4.0,28.0,35500000.0
4,14714.0,2000.0,Adam Keefe,0.095493,C,29.0,UTA,62.0,3.0,604.0,...,-0.2,3.8,5.0,29.94,7.0,81.0,230.0,4.0,30.0,35500000.0
5,14628.0,2000.0,Adonal Foyle,0.100845,C,24.0,GSW,76.0,59.0,1654.0,...,0.2,4.6,5.0,24.90,2.0,82.0,250.0,5.0,25.0,35500000.0
6,14649.0,2000.0,Adrian Griffin,0.014042,SG,25.0,BOS,72.0,47.0,1927.0,...,6.2,2.5,2.0,25.58,0.0,77.0,217.0,2.0,26.0,35500000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12031,18422.0,2007.0,Walter Herrmann,0.034945,PF,27.0,CHA,48.0,12.0,936.0,...,0.4,3.4,4.0,27.60,0.0,81.0,225.0,3.0,28.0,55630000.0
12041,18337.0,2007.0,Yakhouba Diawara,0.012358,SG,24.0,DEN,64.0,19.0,1177.0,...,-0.5,2.7,2.0,24.43,0.0,79.0,225.0,3.0,25.0,55630000.0
12043,18614.0,2007.0,Zach Randolph,0.239679,PF,25.0,POR,68.0,67.0,2425.0,...,2.9,4.3,4.0,25.55,5.0,81.0,253.0,4.0,26.0,55630000.0
12044,18581.0,2007.0,Zaza Pachulia,0.071904,C,22.0,ATL,72.0,47.0,2026.0,...,2.3,4.5,5.0,22.98,3.0,83.0,240.0,5.0,23.0,55630000.0
12045,18442.0,2007.0,Zydrunas Ilgauskas,0.182315,C,31.0,CLE,78.0,78.0,2130.0,...,7.4,5.0,5.0,31.66,8.0,87.0,238.0,5.0,32.0,55630000.0

In [64]:
salary_caps.iloc[1,1] + 1

70000001